### ISSUE TITLE
Buying Mod does not remove society money

### ISSUE THREAD

**Issue by baguscodestudio** [CarlosVergikosk/INRP_MECHANICJOB#11]
Hi, i have installed the mod properly and its working great! The issue is when you buy mod it does not remove any society_mechanic money.

I have checked the code, compared it to ls customs it is the same logic, didn't change anything in the code. Re installed esx_society with the newest latest version. No errors in f8 or even in console.

Thats all i have tried.

**Comment by CarlosVergikosk** [comment]
Try to do some debugg, it can be a problema in your database or something like that... it works fine for me/ no one is reporting problems about that

**Comment by baguscodestudio** [comment]
Sorry to say but it is not working with the latest version of esx. I clean installed the server with latest version of esx basics. Here is proof of the video.

[video](https://imgur.com/a/MlvBOeY)

**Comment by CarlosVergikosk** [comment]
Yes, i havent updated the script yet, im waiting for ESX to be  stable
