### ISSUE TITLE
Anim doesn't work even with radian_animation & carlift is broken car mods

### ISSUE THREAD

**Issue by SpecKnS** [CarlosVergikosk/INRP_MECHANICJOB#7]
HelIo! Good Aftermoon, my INRP is giving errors, didn't change any files.

I do not speak English

![20191116121936_1](https://user-images.githubusercontent.com/39608191/68995363-b89c5f00-086b-11ea-891a-807ea3e167ca.jpg)
![20191116121919_1](https://user-images.githubusercontent.com/39608191/68995364-b89c5f00-086b-11ea-959a-924feb8474c8.jpg)

**Comment by CarlosVergikosk** [comment]
First print - the error is caused by your mythic_notify. 
Second print have been solved recently, i recommend you to look the forum about those errors ;)

**Comment by SpecKnS** [comment]
Vou verificar, obrigado pela atenção!

**Comment by borbaserver** [comment]
Aonde ativo as animações? No **mythic_notify**?

![image](https://user-images.githubusercontent.com/39608191/69273942-1d332300-0bb8-11ea-98d7-cb737da8c694.png)

**Comment by borbaserver** [comment]
Ou config.lua em **INRP_MECHANIC** removendo os _(--)_

**Comment by borbaserver** [comment]
![image](https://user-images.githubusercontent.com/39608191/69274517-443e2480-0bb9-11ea-8e85-713ee2b51b9f.png)
