### ISSUE TITLE
Unico problema é nos props, não consigo fazer eles funcionar...

### ISSUE THREAD

**Issue by SpecKnS** [CarlosVergikosk/INRP_MECHANICJOB#8]
Eu já baixei o **mythic_notify** varias vezes atualizando e o mesmo não funciona, existe alguma configuração? Por favor, me ajude, as animações eu consegui!

![image](https://user-images.githubusercontent.com/39608191/69276549-75b8ef00-0bbd-11ea-97da-9cae369a5b7f.png)

**Comment by SpecKnS** [comment]
Acabei de baixar e após um tempo o problema volta....

![image](https://user-images.githubusercontent.com/39608191/69276754-c597b600-0bbd-11ea-9b7a-e7ac4fe56aa7.png)

**Comment by CarlosVergikosk** [comment]
i just fixed that problemn in my last update ;)
